### PR TITLE
update install instructions for neo4j-php-client

### PR DESCRIPTION
**Pull request by jwong-dayspring**
Change the composer command from `install` to `require` and specify `laudis/neo4j-php-client` instead of ambiguous `neo4j-php-client`

### CODE REVIEW

**Comment by moxious** [comment]
@transistive could you have a look?

**Comment by transistive** [comment]
Perfect! Looks like an oversight on my part. Thanks for the fix!

**Comment by transistive** [comment]
It looks I cannot approve it, so someone else has to :+1:

**Comment by moxious** [comment]
I can do it.  No problem to merge this, just wanted a second set of eyes on it, thank you!

**Pull request merged**
