### PR TITLE
Update example project page

### PR DESCRIPTION
**Pull request by fbiville**

### CODE REVIEW

**Comment by jexp** [comment]
we should keep the images here as a "source of truth" even if they are finally pulled from the CDN

**Comment by jexp** [comment]
Can we add default connection details for to the page (and the projects)

neo4j+s://demo.neo4jlabs.com
user movies
password movies
database movies

And explain how to do it on sandbox / aura

**Comment by jexp** [comment]
And if we remove heroku as a deployment option for the app(s) what would be other good options to deploy it quickly?
(besides running it locally)

**Comment by fbiville** [comment]
> And if we remove heroku as a deployment option for the app(s) what would be other good options to deploy it quickly?
> (besides running it locally)

I'm not sure :)
At first, I was thinking of just linking to https://neo4j.com/cloud/, but that does not really solve the "deploy quickly" part.
I can keep Heroku.

**Comment by jexp** [comment]
Do you have other **easy** options that make sense?  What would be the quick go to for a modern developer?

GCP run functions? Aws (lambda?) Netlify?

**Comment by fbiville** [comment]
@jexp ready for review
I decided to leave Heroku as-is for now.
Neo4j Aura and Sandbox have been added to the `Data Setup` section.

**Comment by jexp** [comment]
Cool thanks a lot, I did some small updates and clean up.

We should make sure that all projects use the same environment variables as a fallbacks (that I used in Heroku, we should probably call them out in the Deployment section.

**Pull request merged**
