### PR TITLE
Remove CypherNET from .Net guide

### PR DESCRIPTION
**Pull request by fbiville**

### CODE REVIEW

**Comment by jexp** [comment]
I wonder if we should remove it altogether? Was there any recent activity on that driver / repo?

**Comment by fbiville** [comment]
The latest activity was from 2 years ago, but it uses the quite stable Cypher transactional endpoint so it may be OK to keep it? What do you think?

**Comment by jexp** [comment]
No reaction to any of the issues or pull requests, I would remove it.

**Comment by fbiville** [comment]
Cypher.NET now removed.

**Review by JMHReif — APPROVED** [review]

**Pull request merged**
