### PR TITLE
Update driver versions

### PR DESCRIPTION
**Pull request by fbiville**

### CODE REVIEW

**Comment by jexp** [comment]
@fbiville can you rebase? there is an antora.yml conflict.

*We also need to check* if after the driver version update all the pages still render that include files from the driver repos.

**Comment by fbiville** [comment]
Now rebased, let me take a look at the possible links based on these driver versions.

**Comment by fbiville** [comment]
Thanks for the warning @jexp, it seems one link was indeed broken.

**Comment by jexp** [comment]
Let me know if it's ok to review.

**Comment by fbiville** [comment]
I think it's good for review @jexp

**Review by JMHReif — APPROVED** [review]

**Pull request merged**
